# config.yaml
eager_task_factory: false
log_config: log_config.json
apps:
  app:
    port: 8000
    host: "localhost"
    log_config: log_config.json
    sub_apps:
      pet_service:
        path: "/pet"
        app: "services.pet_service:app"
        kwargs: 
          database_url: "sqlite:///./.sqlite_db/pets.db"
      user_service:
        path: "/user"
        app: "services.user_service:app"
        kwargs:
          pet_service_url: "http://localhost:8000/pet"
          database_url: "sqlite:///./.sqlite_db/user.db"
  # app1:
  #   port: 8001
  #   host: "localhost"
  #   sub_apps:
  #     template_service:
  #       path: "/template"
  #       app: "services.template_service:app" # ASGI 'lifespan' protocol appears unsupported??
