# config_schema.yaml
type: object
properties:
  sub_routes:
    type: object
    additionalProperties:
      type: object
      properties:
        path:
          type: string
        app:
          type: string
      required: [path, app]
required: [sub_routes]
