# config_schema.yaml
type: object
properties:
  eager_task_factory:
    type: boolean
  apps:
    type: object
    additionalProperties:
      type: object
      properties:
        port:
          type: number
        host:
          type: string
        sub_apps:
          type: object
          additionalProperties:
            type: object
            properties:
              path:
                type: string
              app:
                type: string
